[build]
  command = "# no build command needed for now"
  publish = "."
  functions = "netlify/functions"

[dev]
  framework = "#static"
  
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200 

[functions]
  node_bundler = "esbuild"

# Enable Netlify KV store
[template.environment]
  NETLIFY_ENABLE_KV = "true" 